# Plugins:
plugins:
  - jekyll-paginate
  - jekyll-coffeescript

# Basic information:
title: Sławomir Czerwiński
url: https://czerwinski.it
email: slawomir@czerwinski.it

# Social media:
github: sczerwinski
linkedin: sczerwinski
stackoverflow: sczerwinski
ko-fi: sczerwinski

# Sass:
sass:
  sass_dir: _sass
  style: compressed

# Blog:
paginate: 3
paginate_path: "/posts/:num/"

# Syntax coloring:
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include hidden folders:
include: [".well-known"]

# Defaults:
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"