# Plugins:
gems: [jekyll-paginate]

# Basic information:
title: Sławomir Czerwiński
url: https://czerwinski.it
email: slawomir@czerwinski.it

# Social media:
github: sczerwinski
twitter: s_czerwinski
linkedIn: sczerwinski

# Links:
braveUrl: https://brave.com/cze677

# Blog:
paginate: 5
paginate_path: "/posts/:num/"

# Syntax coloring:
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Include hidden folders:
include: [".well-known"]

# Defaults:
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"