# Plugins:
gems: [jekyll-paginate]

# Basic information:
title: Sławomir Czerwiński
url: http://czerwinski.info.pl
email: slawomir@czerwinski.info.pl

# Social media:
twitter: s_czerwinski
linkedIn: sczerwinski

# Blog:
paginate: 2
paginate_path: "/posts/:num/"

# Syntax coloring:
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
