---
layout: null
sitemap:
exclude: 'yes'
---
openapi: 3.0.0
info:
  version: '1.0'
  title: {{ site.title }} – Blog API
  description: API documentation for my personal blog.
  license:
    name: Apache License Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
servers:
  - url: {{ site.url }}/api
    description: {{ site.title }} – Blog API
paths:
  /links.json:
    get:
      summary: External links
      description: Returns list of links related to the author of the blog.
      responses:
        '200':
          description: List of links
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: GitHub
                    type:
                      type: string
                      example: github
                    url:
                      type: string
                      example: https://github.com/sczerwinski
        default:
          description: Unexpected error
  /news.json:
    get:
      summary: Latest news
      description: Returns list of latest news publish on the blog website.
      responses:
        '200':
          description: List of news
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    title:
                      type: string
                      example: New post published
                    abstract:
                      type: string
                      example: In my new post, I describe…
                    url:
                      type: string
                      example: {{ site.url }}/2019/03/20/random-post.html
                    date:
                      type: string
                      example: '2019-03-20'
        default:
          description: Unexpected error
  /posts.json:
    get:
      summary: Blog posts
      description: Returns list of blog posts.
      responses:
        '200':
          description: List of blog posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: random-post
                    title:
                      type: string
                      example: Random Post
                    abstract:
                      type: string
                      example: In my new post, I describe…
                    image:
                      type: string
                      example: {{ site.url }}/assets/img/post/2019-03-20-random-post.png
                    tags:
                      type: array
                      items:
                        type: string
                        example: tagname
                    url:
                      type: string
                      example: {{ site.url }}/2019/03/20/random-post.html
                    date:
                      type: string
                      example: '2019-03-20'
        default:
          description: Unexpected error
  /projects.json:
    get:
      summary: Open-source projects
      description: Returns list of open-source projects.
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: random-project
                    title:
                      type: string
                      example: Random Project
                    abstract:
                      type: string
                      example: My random open-source project…
                    url:
                      type: string
                      example: {{ site.url }}/projects/random-project.html
        default:
          description: Unexpected error